id: P004551
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD53275
  title: སེམས་གཏམ
  author: ''
  volumes:
    51edd9beb16d40578929528b4eb4c0be:
      image_group_id: I1PD54414
      title: ''
      volume_number: 1
      total_pages: 172
      base_file: v001.txt
